apiVersion: v1
kind: Service
metadata:
  name: fastapi-llm-assistant
  labels:
    app: fastapi-llm-assistant
spec:
  selector:
    app: fastapi-llm-assistant
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  type: ClusterIP